### PR TITLE
compiled aubio

### PR DESCRIPTION
**Pull request by jithesh82**
Hello there,

Thanks a lot for your great work!  I followed the instructions on your page and examples, and was able to compile the package aubio.  I have updated my fork with meta.yaml .  Would you be able to merge this change?  Or let me know what I need to do more that the package can be incorporated.  Thank you!

Good luck!
-Jithesh

### CODE REVIEW

**Comment by mhsmith** [comment]
Thanks very much. To merge a new package, we need a test file which does some basic checks. See the bottom of pypi/README.md for instructions; I pushed some updates a few minutes ago.

Please add a test and let me know which Python versions and ABIs you've run it on.

**Comment by jithesh82** [comment]
Thanks for your kind response and the new instructions. I wasn't sure exactly were to add the package name for testing in the gradle file.  I used with an 'install package' in the pip block.  This makes it clear.

**Comment by mhsmith** [comment]
> I used with an 'install package' in the pip block. 

Yes, that's where you would add it in a normal app, but the pkgtest app has a helper function in its build.gradle file which adds the package and its test file at the same time.

**Comment by jithesh82** [comment]
Oh, I got that from you gradle documentation.  I didn't understand it fully.  Now it works like a charm. Thank you!
Now I have added the test.py file.  
Python version: Python 3.8
ABI:  All 4 of them
I added chaquopy.patch.  I tested with patch only once, it seems to work.  I am not sure the syntax is fully correct.  I was manually editing the setup.py when building for each ABI.  
I tested on 4 ABI phones on android studio.  The tests runs without any errors.  

Your work is really amazing. Thank you for your contribution!

**Comment by mhsmith** [comment]
Thanks very much: this package is now in the public repository for Python 3.8, 3.9 and 3.10.

**Comment by jithesh82** [comment]
Thank you so much for all your help and work 🙏.

**Pull request merged**
