### PR TITLE
Add smoke tests for qutip.

### PR DESCRIPTION
**Pull request by hodgestar**

### CODE REVIEW

**Comment by mhsmith** [comment]
Thanks, I'm on holiday for the next week and a half, but I'll deal with this when I come back.

**Comment by hodgestar** [comment]
Enjoy your holiday! :D

**Comment by mhsmith** [comment]
I've converted the tests to unittest format, because that's what's used by the test harness. And I've moved the packages to the [public repository](https://chaquo.com/pypi-13.1/qutip/), so your app won't need the `--extra-index-url` option anymore. 

I've also added builds of the current stable version, 4.7.1, and I've edited the tests to be compatble with both qutip 4 and 5. They all pass on both versions, except for this test which fails on qutip 5:

```
FAIL: test_qobj_methods (test.TestQutip)
----------------------------------------------------------------------   
Traceback (most recent call last):
  File "/home/smith/git/chaquo/chaquopy/server/pypi/packages/qutip/test.py", line 97, in test_qobj_methods
    assert_qobj_data(ev1, [
  File "/home/smith/git/chaquo/chaquopy/server/pypi/packages/qutip/test.py", line 7, in assert_qobj_data
    np.testing.assert_allclose(q.full(), data)
  File "/home/smith/.venv/pkgtest/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 1590, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg), 
  File "/home/smith/.pyenv/versions/3.8.12/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/smith/.venv/pkgtest/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 862, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 2 / 2 (100%)
Max absolute difference: 1.57641088
Max relative difference: 2.
 x: array([[0.615412+0.j      ],
       [0.      -0.788205j]])
 y: array([[-0.615412+0.j      ],
       [ 0.      +0.788205j]])
```

I get the same results on Linux, so I guess this is a change in behavior between qutip 4 and 5. Is this expected, or is it a bug in one of the versions?

**Comment by hodgestar** [comment]
These values are normalized eigenvectors and so ambiguous up to a sign (in this case) or more generally a phase. The answers from QuTiP 4 and 5 are thus both correct.

Something like:
```
ev0 = ev0 * np.sign(ev0[0, 0].real)
ev1 = ev1 * np.sign(ev1[0, 0].real)
```
Rotating by the phase of `ev[0, 0]` would be mathematically cleaner but I think would also make debugging a bit harder.

**Comment by hodgestar** [comment]
Thank you for going to all of the trouble to add QuTiP 4 and to make the tests work on both!

**Pull request merged**
