### PR TITLE
Cryptography 42 and rust

### LINKED ISSUE #657: Cryptography 36.0.2 (and rust support)
Here are some notes I took when building the [cryptography 36.0.2](https://github.com/emanuele-f/chaquopy-wheels) python module in Chaquopy, which was needed to run mitmproxy 8.0.0. I hope this will be useful to integrate it in the officially supported packages.

## Overview

mitmproxy 8.0.0 depends on the new cryptography 36.x module, for which `rust` is now mandatory.
cryptography uses `setuptools_rust` to build native shared objects and `pyo3` to invoke them from python.

Here the relevant part of the dependency tree:

```
mitmproxy
  cryptography
    setuptools_rust
      rust
    pyo3
      python
```

Other than rust setup for cross-compilation, the problematic part is that cryptography uses `pyo3 v0.15.1`, which requires a python interpreter to be cross-compiled for the target architecture (and it looks for `_sysconfigdata*` in the python lib folder). In theory, both pyo3 and cryptography support building *abi3* modules, which work regardless of the specific python version and could
be built without an existing python interpreter. However, this possibility is only added in [pyo3 0.16.4](https://pyo3.rs/v0.16.4/building_and_distribution.html), which is not currently supported by cryptography. See https://github.com/PyO3/pyo3/discussions/2310 for more details.

So, in order to build the cryptography module, we currently need:

- Install rust and configure it for the cross compilation
- Cross compile python

With some tricks, it's possible to compile only the core of python without the need to also cross-compile its dependencies. In fact, the pyo3 shared modules of cryptography will be linked against the *soname* used by python library shipped with chaquopy.

## Preparing the build environment

The following instructions are meant for building on an archlinux host *without* docker. Install requirements (most requirements not listed here, see `target/Dockerfile`)

```
pacman -S patchelf
```

Copy the Android toolchains used by chaquopy:

```
docker build -t chaquopy-base -f base.dockerfile .
docker build -t chaquopy-target target

# replace 62b7d2f98872 with the chaquopy-target container ID
cd target
docker cp 62b7d2f98872:/root/target/toolchains toolchains
```

To avoid polluting the build machine, use an overlayfs to install all the stuff:

```sh
cd /home/emanuele/src/build-wheel
mkdir build
cd build
rm -rf sysroot
mkdir -p sysroot overlay workdir

# NOTE: to refresh the lowerdir when mounted, run "sudo mount -o remount overlay"
sudo mount -t overlay overlay -o lowerdir=/,upperdir=./sysroot,workdir=./workdir ./overlay
sudo arch-chroot ./overlay
```

Build and install the exact python version required by Chaquopy:

```sh
version=3.8.7

cd /home/emanuele/src/build-wheel/build
wget https://www.python.org/ftp/python/$version/Python-$version.tgz

tar -xf Python-$version.tgz
cd Python-$version
./configure --prefix=/usr
make -j $(nproc)
make install

# verify
python3.8 --version
```

Install rust and libraries required for cross-compilation in rust

```sh
pacman -Rs rustup rust
curl https://sh.rustup.rs -sSf | sh -s -- -y
source "$HOME/.cargo/env"

# required for cross-compilation
rustup target add aarch64-linux-android
rustup target add arm-linux-androideabi
rustup target add i686-linux-android
rustup target add x86_64-linux-android

# Verify installed cross-compilation libraries
rustc --print target-list | grep android

# install requirements, they will be needed to build cryptography
cd /home/emanuele/src/build-wheel/server/pypi
pip3.8 install -r requirements.txt
```

## Building for an ABI

These steps must be performed for each Android ABI.

First select the target ABI:

```
# only pick the target ABI of choice
export ARCH="armeabi-v7a" CPU="arm"     TOOL_PREFIX="arm-linux-androideabi" TOOL_CFLAGS="-march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb" TOOL_LDFLAGS="-march=armv7-a -Wl,--fix-cortex-a8"
export ARCH="arm64-v8a"   CPU="aarch64" TOOL_PREFIX="aarch64-linux-android" TOOL_CFLAGS="" TOOL_LDFLAGS=""
export ARCH="x86"         CPU="x86"     TOOL_PREFIX="i686-linux-android"    TOOL_CFLAGS="" TOOL_LDFLAGS=""
export ARCH="x86_64"      CPU="x86_64"  TOOL_PREFIX="x86_64-linux-android"  TOOL_CFLAGS="" TOOL_LDFLAGS=""
```

Setup the environment for cross compilation:

```
version=3.8.7
cd /home/emanuele/src/build-wheel/build

# cleanup and setup
rm -rf $ARCH/sysroot/usr $ARCH/Python-$version
mkdir -p $ARCH/sysroot/usr/lib $ARCH/sysroot/usr/include
tar -C $ARCH -xf Python-$version.tgz

TOOLCHAIN=`readlink -f ../target/toolchains`
SYSROOT=`readlink -f $ARCH/sysroot`

# copy headers from the toolchain to the sysroot
cp -r $TOOLCHAIN/$ARCH/sysroot/usr/* $SYSROOT/usr

# (OPTIONAL) extend sysroot with python deps, not actually needed by pyo3
#cp -r deps/OpenSSL-for-Android-Prebuilt/openssl-1.1.1k-clang/include/* $ARCH/sysroot/usr/include
#cp -r deps/libcrypt_0.2-5_aarch64/usr/* $ARCH/sysroot/usr
#...

# Needed to cross compile python (some may not be needed)
export CC="$TOOLCHAIN/$ARCH/bin/$TOOL_PREFIX-gcc"
export CXX="$TOOLCHAIN/$ARCH/bin/$TOOL_PREFIX-g++"
export AR="$TOOLCHAIN/$ARCH/bin/$TOOL_PREFIX-ar"
export AS="$TOOLCHAIN/$ARCH/bin/$TOOL_PREFIX-as"
export LD="$TOOLCHAIN/$ARCH/bin/$TOOL_PREFIX-ld"
export LDSHARED="$TOOLCHAIN/$ARCH/bin/$TOOL_PREFIX-gcc -shared"
export RANLIB="$TOOLCHAIN/$ARCH/bin/$TOOL_PREFIX-ranlib"
export STRIP="$TOOLCHAIN/$ARCH/bin/$TOOL_PREFIX-strip --strip-unneeded"
export NM="$TOOLCHAIN/$ARCH/bin/$TOOL_PREFIX-nm"
export READELF="$TOOLCHAIN/$ARCH/$TOOL_PREFIX/bin/readelf"
export CROSS_COMPILE_TARGET=yes
export CFLAGS="-fPIC -DANDROID --sysroot=$SYSROOT $TOOL_CFLAGS"
export CXXFLAGS="$CFLAGS"

# Flags taken from build-wheel.py
export LDFLAGS="--sysroot=$SYSROOT -Wl,--no-undefined -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libunwind.a $TOOL_LDFLAGS"
```

Cross compile python

```
cd $ARCH/Python-$version
./configure --build=x86_64-unknown-linux-gnu --host=$CPU-linux-android --enable-shared --prefix=`readlink -f ../sysroot/usr` \
    ac_cv_file__dev_ptmx=no ac_cv_file__dev_ptc=no ac_cv_have_long_long_format=yes ac_cv_buggy_getaddrinfo=no

# patch to support Android API 19
# chaquopy targets API 19 on armv7a/x86, which is not fully supported by python https://bugs.python.org/issue36162
# the API level is specified via the "--target=" arg inside the $TOOL_PREFIX-gcc script
sed -i 's/^#define HAVE_SENDFILE 1$/\/* #undef HAVE_SENDFILE *\//g' pyconfig.h
sed -i 's/^#define HAVE_TRUNCATE 1$/\/* #undef HAVE_TRUNCATE *\//g' pyconfig.h
sed -i 's/^#define HAVE_WCSFTIME 1$/\/* #undef HAVE_WCSFTIME *\//g' pyconfig.h

# build (ignore errors, they occur because of missing dependencies, but we are only interested in libpython and related _sysconfigdata)
make -j $(nproc)
make install

# Patch SONAME to correspond to the chaquopy "libpython3.8.so"
# check with x86_64-linux-android-readelf -Wa $SYSROOT/usr/lib/libpython3.8.so | grep SONAME
mv $SYSROOT/usr/lib/libpython3.8.so{.1.0,}
patchelf --set-soname libpython3.8.so $SYSROOT/usr/lib/libpython3.8.so
```

Finally, build cryptography (assume `rust_cross_compile.patch` is applied (see below), which sets `PYO3_CROSS_LIB_DIR`):

```
cd /home/emanuele/src/build-wheel/server/pypi

python3.8 ./build-wheel.py --toolchain ../../target/toolchains/$ARCH cryptography
```

If build successful, you can retrieve the built wheel from outside the overlayfs in the `build-wheel/sysroot` folder.

## build-wheel patches

`rust_cross_compile.patch`:
```patch
--- src-original/setup.py
+++ src/setup.py
@@ -10,6 +10,16 @@ import sys
 
 from setuptools import setup

+# https://doc.rust-lang.org/rustc/codegen-options/index.html
+os.environ["RUSTFLAGS"] = f"-C linker={os.environ['CC']}"
+os.environ["CARGO_BUILD_TARGET"] = os.environ['CHAQUOPY_TRIPLET']
+
+# https://pyo3.rs/v0.15.2/building_and_distribution.html
+os.environ["PYO3_PYTHON"] = f"python{os.environ['CHAQUOPY_PYTHON']}"
+os.environ["PYO3_CROSS_PYTHON_VERSION"] = os.environ['CHAQUOPY_PYTHON']
+os.environ["PYO3_CROSS_LIB_DIR"] = f"{os.environ['RECIPE_DIR']}/../../../../build/{os.environ['CHAQUOPY_ABI']}/sysroot/usr/lib"
+#print(os.environ)
+
 try:
     from setuptools_rust import RustExtension
 except ImportError:
```

`cryptography meta.yaml`:
```yaml
package:
  name: cryptography
  version: 36.0.2

requirements:
  build:
    - cffi 1.13.2
    - setuptools-rust 1.2.0
  host:
    - openssl
```

## Add rust to the docker build script

```
# Install rust and rustup
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y

# Install crates needed for cross compilation (note you need to re-run all the build commands)
# https://rust-lang.github.io/rustup/cross-compilation.html
Run source $HOME/.cargo/env && \
    rustup target add x86_64-linux-android && \
    rustup target add i686-linux-android && \
    rustup target add aarch64-linux-android && \
    rustup target add armv7-linux-androideabi
```

### LINKED ISSUE #1141: build-wheel sets _PYTHON_HOST_PLATFORM with incorrect format
```
/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc --crate-name cryptography_rust --edition=2021 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=233 --crate-type cdylib --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no -C overflow-checks=on --cfg 'feature="default"' --cfg 'feature="extension-module"' -C metadata=6a2eca71f96f7f26 --out-dir /root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/src/src/rust/target/release/deps -C strip=debuginfo -L dependency=/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/src/src/rust/target/release/deps --extern asn1=/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/src/src/rust/target/release/deps/libasn1-3cbd8c400f93aebb.rlib --extern cfg_if=/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/src/src/rust/target/release/deps/libcfg_if-aaad75c953799a78.rlib --extern cryptography_cffi=/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/src/src/rust/target/release/deps/libcryptography_cffi-f6d1f53d4b4eba67.rlib --extern cryptography_key_parsing=/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/src/src/rust/target/release/deps/libcryptography_key_parsing-bf3a06dc4569f3b6.rlib --extern cryptography_openssl=/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/src/src/rust/target/release/deps/libcryptography_openssl-7ea2495f600dab58.rlib --extern cryptography_x509=/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/src/src/rust/target/release/deps/libcryptography_x509-dcfd9e64a59670f0.rlib --extern cryptography_x509_verification=/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/src/src/rust/target/release/deps/libcryptography_x509_verification-b4fcd3ced752b1c7.rlib --extern foreign_types_shared=/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/src/src/rust/target/release/deps/libforeign_types_shared-b4c802ac253d35ff.rlib --extern once_cell=/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/src/src/rust/target/release/deps/libonce_cell-92ab50a58aad97d5.rlib --extern openssl=/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/src/src/rust/target/release/deps/libopenssl-a842c4610fd1f319.rlib --extern openssl_sys=/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/src/src/rust/target/release/deps/libopenssl_sys-194f651fc41ddae3.rlib --extern pem=/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/src/src/rust/target/release/deps/libpem-c4abfd424caba6e8.rlib --extern pyo3=/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/src/src/rust/target/release/deps/libpyo3-8f6b6dac58ebb9e5.rlib --extern self_cell=/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/src/src/rust/target/release/deps/libself_cell-a6952d443b37ada8.rlib -L native=/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/src/src/rust/target/release/build/cryptography-cffi-7a83c08114839c33/out -L native=/usr/local/openssl/lib --cfg 'CRYPTOGRAPHY_OSSLCONF="OPENSSL_NO_SSL3_METHOD"'`
warning: unused import: `crate::error::CryptographyResult`
 --> src/lib.rs:7:5
  |
7 | use crate::error::CryptographyResult;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `std::env`
  --> src/lib.rs:10:5
   |
10 | use std::env;
   |     ^^^^^^^^

warning: unused variable: `cipher_name`
   --> src/backend/aead.rs:548:13
    |
548 |         let cipher_name = match key.as_bytes().len() {
    |             ^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_cipher_name`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: `cryptography-rust` (lib) generated 3 warnings (run `cargo fix --lib -p cryptography-rust` to apply 3 suggestions)
    Finished release [optimized] target(s) in 35.28s
Traceback (most recent call last):
  File "/root/miniconda3/envs/build-wheel/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/root/miniconda3/envs/build-wheel/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/root/miniconda3/envs/build-wheel/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
    return _build_backend().build_wheel(wheel_directory, config_settings,
  File "/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/env/lib/python3.10/site-packages/setuptools/build_meta.py", line 410, in build_wheel
    return self._build_with_temp_dir(
  File "/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/env/lib/python3.10/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
    self.run_setup()
  File "/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/env/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 1, in <module>
  File "/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/env/lib/python3.10/site-packages/setuptools/__init__.py", line 104, in setup
    return distutils.core.setup(**attrs)
  File "/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/env/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
    return run_commands(dist)
  File "/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/env/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    dist.run_commands()
  File "/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/env/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/env/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 368, in run
    self.run_command("build")
  File "/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/env/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/env/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/env/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
    self.run_command(cmd_name)
  File "/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/env/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/env/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
    super().run_command(command)
  File "/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/env/lib/python3.10/site-packages/setuptools_rust/setuptools_ext.py", line 160, in run
    super().run()
  File "/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/env/lib/python3.10/site-packages/setuptools_rust/setuptools_ext.py", line 168, in run
    build_rust.run()
  File "/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/env/lib/python3.10/site-packages/setuptools_rust/command.py", line 100, in run
    self.run_for_extension(ext)
  File "/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/env/lib/python3.10/site-packages/setuptools_rust/build.py", line 137, in run_for_extension
    self.install_extension(ext, dylib_paths)
  File "/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/env/lib/python3.10/site-packages/setuptools_rust/build.py", line 373, in install_extension
    ext_path = self.get_dylib_ext_path(ext, module_name)
  File "/root/chaquopy/server/pypi/packages/cryptography/build/42.0.5/cp310-cp310-android_21_arm64_v8a/env/lib/python3.10/site-packages/setuptools_rust/build.py", line 460, in get_dylib_ext_path
    host_arch = host_platform.rsplit("-", 1)[1]
IndexError: list index out of range
build-wheel: Error: Backend subprocess exited when trying to invoke build_wheel
(build-wheel) [root@ecs-weichain pypi]# IndexError: list index out of range
```

### LINKED ISSUE #1175: cryptography for Python 3.11 or later
Is it possible to add python 3.11 build wheel support to the cryptography library? I need to use some asyncio low level socket methods (sock_recvfrom, sock_recvfrom_into, sock_sendto) they were added in python3.11, they are not available on python3.10. Anyway thanks for your work.Especially after discovering chaquo, it feels like opening the door to a new world. There is nothing cooler than being able to develop android apps with hybrid development using python. Thanks anyway for your work.This is really an amazing and great project!
[Low-level asynchronous socket methods added in python version 3.11](https://docs.python.org/zh-cn/3.11/library/asyncio-eventloop.html#working-with-socket-objects-directly)

### PR DESCRIPTION
**Pull request by emanuele-f**
This adds support for building PyO3 modules like `cryptography` which depend on `pyo3 >= 0.16.4`.
Building rust modules requires installing the rust compiler android targets as follows:

```
# install the stable rust version
# Note cryptography 42 requires Rust >= 1.63.0
curl https://sh.rustup.rs -sSf | sh -s -- -y

# add the android targets for cross compilation
rustup target add aarch64-linux-android
rustup target add arm-linux-androideabi
rustup target add i686-linux-android
rustup target add x86_64-linux-android
```

Compared to https://github.com/chaquo/chaquopy/issues/657, it's now possible to compile the cryptography module without issues because they migrated to PyO3 0.20, which removes the need to rebuild python, as sysconfig modules are not needed.

Moreover, since chaquopy updated the ndk to 26, this fixes `ld: error: unable to find library -lunwind` in recent Rust versions (see https://github.com/rust-lang/rust/issues/103673), removing the constrain to use old Rust versions like 1.60; it's now possible to just use the latest stable Rust version. For example, it's now possible to compile the latest `mitmproxy_rs` module which requires a recent Rust version (see https://github.com/emanuele-f/chaquopy/tree/mitmproxy-11/server/pypi/packages/mitmproxy-rs); a separate PR will be provided to include this module in the supported packages.

Ps. double check if https://github.com/chaquo/chaquopy/commit/4461ddaad28c422d7e7ece57b4ebe44f2665bd3a breaks anything, as I can see that #1141 is still open even if the issue was identified.

* Fixes #657
* Fixes #1175 
* Fixes #1141

### CODE REVIEW

**Comment by mhsmith** [comment]
Thanks very much, I'll look at this as soon as I can.

**Comment by Michu44** [comment]
@emanuele-f thank you so much for your contributions!
I have been trying to build cryptography 43 for the past 2 days, and still not much luck.

I've seen your email around here somewhere... any chance I can shoot you a direct message or Email somewhere? I could really use your help and we are happy to pay you if you could help us solve our current issues.

**Comment by emanuele-f** [comment]
Hi @Michu44 , which python version are you targetting? I only tested this with Python 10.

After installing the rust toolchain and android targets as explained above, you should be able to build cryprography as any normal wheel, with the standard build-wheel.py invocation. Which errors do you get?

My email is black.silver@hotmail.it but probably better to discuss here, as it would be beneficial for other people too. Also my intention is to allow anyone to build this without any issues

**Comment by emanuele-f** [comment]
Ps. building cryptography 43.0.1 for Python 3.10 from this PR branch requires minimal changes, just apply the following patch:

```patch
diff --git a/server/pypi/packages/cryptography/meta.yaml b/server/pypi/packages/cryptography/meta.yaml
index 0d042e84..59e63fd0 100644
--- a/server/pypi/packages/cryptography/meta.yaml
+++ b/server/pypi/packages/cryptography/meta.yaml
@@ -1,6 +1,6 @@
 package:
   name: cryptography
-  version: "42.0.8"
+  version: "43.0.1"
 
 requirements:
   build:
diff --git a/server/pypi/packages/cryptography/patches/pyo3_no_interpreter.patch b/server/pypi/packages/cryptography/patches/pyo3_no_interpreter.patch
index 3f03ced5..2d0b9d65 100644
--- a/server/pypi/packages/cryptography/patches/pyo3_no_interpreter.patch
+++ b/server/pypi/packages/cryptography/patches/pyo3_no_interpreter.patch
@@ -1,11 +1,11 @@
 --- src-original/src/rust/Cargo.toml
 +++ src/src/rust/Cargo.toml
-@@ -10,7 +10,7 @@
+@@ -17,7 +17,7 @@
  [dependencies]
  once_cell = "1"
  cfg-if = "1"
--pyo3 = { version = "0.20", features = ["abi3"] }
-+pyo3 = { version = "0.20", features = ["abi3", "abi3-py310"] }
- asn1 = { version = "0.15.5", default-features = false }
+-pyo3 = { version = "0.22.2", features = ["abi3"] }
++pyo3 = { version = "0.22.2", features = ["abi3", "abi3-py310"] }
+ asn1 = { version = "0.16.2", default-features = false }
  cryptography-cffi = { path = "cryptography-cffi" }
- cryptography-key-parsing = { path = "cryptography-key-parsing" }
+ cryptography-keepalive = { path = "cryptography-keepalive" }
```

**Comment by Michu44** [comment]
@emanuele-f Thank you so much for the patch. I'll try and build this using your current code base then.
The end-goal for me is to get the current pyatv library to work on chaquopy, as it seams only cryptography seams to be missing at this point. I'll try and figure it out again with your PR.

**Comment by Michu44** [comment]
@emanuele-f I'm targeting either 3.10 or 3.11 as pyatv is working on both.

**Comment by mhsmith** [comment]
I've now released `cryptography` 42.0.8 wheels for Python 3.10, 3.11, 3.12 and 3.13. Thanks again!

**Comment by maciekglowka** [comment]
Hi, thanks for your work on the Rust support :)
Would this approach work for crates that don't support ABI3 ? I am currently trying to build pydantic core, but due to a `jiter` dependency I can't use this feature on PyO3.
[otherwise I keep getting linking errors with libgcc as previously]

**Comment by emanuele-f** [comment]
> Would this approach work for crates that don't support ABI3 ?

Hello, no, for non-ABI3 modules currently you will still need to cross compile the Python interpreter as explained in https://github.com/chaquo/chaquopy/issues/657

**Comment by maciekglowka** [comment]
Shoot....thanks for the quick answer though. I was worried that'd be the case (after spending half a day again trying different configurations).
I managed to even work around the `jiter` thing (it has cfg flags). But then pydantic itself import loads of non-abi3 types, so...

**Comment by GewoonJaap** [comment]
> @emanuele-f I'm targeting either 3.10 or 3.11 as pyatv is working on both.

How did you manage to solve: uto-reconnect error: TypeError: type 'cryptography.hazmat.bindings._rust.openssl.aead.ChaCha20Poly1305' is not an acceptable base type

For pyatv? I can only seem to use pyatv up to 0.10 after that I get this error

**Comment by mhsmith** [comment]
Please keep all discussion on that issue in #1438.

**Pull request merged**
